spring:
  config:
    import: "optional:nacos:hm-gateway-service.yaml"
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: gateway-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: gw-flow

hm:
  nacos:
    addr: 127.0.0.1:8848
    namespace: dev
  redis:
    host: 127.0.0.1
    port: 6379
    password:
