hm:
  swagger:
    title: 黑马商城支付服务接口文档
    package: com.hmall.pay.controller
  auth:
    excludePaths:
      - /error
      - /doc.html
      - /webjars/**
      - /swagger-resources/**
      - /v2/api-docs/**
      - /v3/api-docs/**
      - /favicon.ico
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
